CREATE DATABASE IF NOT EXISTS data;
USE data;

CREATE TABLE IF NOT EXISTS word (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    arrived_at VARCHAR(50) NOT NULL,
    leaved_at VARCHAR(50) NOT NULL
);


